language: python
python:
  - "3.4"
dist: trusty
before_install:
    - git clone https://github.com/google/re2.git
    - cd re2 && make && sudo make install && cd ..
install:
  - pip install -r requirements.txt
# command to run tests
script: python -m rules.de